export default defineEventHandler(() => {
  const R2 = 'https://cdn.bytewoof.dog/gallery'
  return [
    {
      loc: '/',
      images: [
        { loc: `${R2}/byte-bust.webp`,         title: 'bust',                  caption: 'bust by Noah' },
        { loc: `${R2}/byte-lick.webp`,          title: 'blep',                  caption: 'blep by Noah' },
        { loc: `${R2}/byte-refsheet.webp`,      title: 'ref sheet',             caption: 'ref sheet by Noah' },
        { loc: `${R2}/byte-puppified.webp`,     title: 'Puppy Pride YCH',       caption: 'Puppy Pride YCH by 14pup' },
        { loc: `${R2}/byte-icon.webp`,          title: 'love emoticon',         caption: 'love emoticon by zanky' },
        { loc: `${R2}/byte-hug.webp`,           title: 'Waiting For Moment YCH', caption: 'Waiting For Moment YCH by velvetbun' },
        { loc: `${R2}/byte-bellyrub.webp`,      title: 'Belly Rub YCH',         caption: 'Belly Rub YCH by kiro' },
        { loc: `${R2}/byte-livevibrantly.webp`, title: 'Live Vibrantly YCH',    caption: 'Live Vibrantly YCH by Kaiju' },
        { loc: `${R2}/byte-goodboy.webp`,       title: 'Good Boy',              caption: 'Good Boy by Deastratit' },
        { loc: `${R2}/byte-sticker-000.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-001.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-002.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-003.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-004.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-005.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-006.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-007.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-008.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-009.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-010.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-011.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-012.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-013.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-014.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-015.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-016.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-017.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-018.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-019.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-020.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-021.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-022.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-023.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-024.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-025.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-026.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-027.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-028.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-029.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-030.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-031.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-032.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-033.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-034.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-035.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-036.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-037.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-038.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-039.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-040.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-041.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-042.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-043.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-044.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-045.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-046.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-047.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-048.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-049.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-050.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-051.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-052.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-053.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-054.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-055.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-056.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-057.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-058.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-sticker-059.webp`, title: 'sticker pack', caption: 'sticker pack by Noah' },
        { loc: `${R2}/byte-tinypup.webp`,   title: 'Tiny Pup',   caption: 'Tiny Pup by Noah' },
        { loc: `${R2}/byte-portrait.webp`,  title: 'Portrait',   caption: 'Portrait by Noah' },
        { loc: `${R2}/byte-isopod.webp`,    title: 'Isopod',     caption: 'Isopod by Noah' },
        { loc: `${R2}/byte-sleepypup.webp`, title: 'Sleepy Pup', caption: 'Sleepy Pup by Noah' },
        { loc: `${R2}/byte-spacepup.webp`,  title: 'Space Pup',  caption: 'Space Pup by Noah' },
      ],
    },
  ]
})
